dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip
branches:
  only:
  - master
notifications:
  email: false

matrix:
  include:
    - python: "2.7"
      env: CRYPTO_VER=1.5.3
    - python: "2.7"
      env: CRYPTO_VER=2.4.2
    - python: "3.4"
      env: CRYPTO_VER=1.5.3
    - python: "3.4"
      env: CRYPTO_VER=2.4.2
    - python: "3.5"
      env: CRYPTO_VER=2.4.2
    - python: "3.6"
    - python: "3.7"
install:
  - if [ -n "$CRYPTO_VER" ]; then pip install cryptography==$CRYPTO_VER; fi
  # Self-install for setup.py-driven deps
  - pip install -e .
  # Dev (doc/test running) requirements
  - pip install -r dev-requirements.txt
script:
  - flake8
  - pytest -v
